version: '3'

services:
  neo4j:
    #image: neo4j:4.4.3-community
    # for M1
    #image: neo4j/neo4j-arm64-experimental:4.3.9-arm64
    container_name: neo4j
    build:
      context: ./neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    # neo4j-admin load --from=./movies-43.dump  --force
    # entrypoint: ["sh", "-c", "tail -f /dev/null"]
    environment: 
      - NEO4J_AUTH=neo4j/lumiere
     